### PR TITLE
Add Prettier

### PR DESCRIPTION
**Pull request by nb**
[prettier](https://github.com/prettier/prettier) is a decent JavaScript auto-formatter. No need to either argue about code style or even write in specific style, `prettier` takes care.

This PR both adds the infrastructure to run `prettier` before a commit and formats the code. All the infra changes are in `package.json`.

The suggested style is similar to `standard`, I added trailing-commas, but I don’t feel strongly about any of the options, so if you like the general idea, but dislike some of the options, feel free to override them.

Editor integration details: https://github.com/prettier/prettier#editor-integration
What it took me to set it up in `neovim`: https://github.com/nb/dotfiles/commit/7839ff69ef8b6a807cb746630caf9a330e3647bd

### CODE REVIEW

**Comment by heapwolf** [comment]
Cool! I'm `+1` as long as i can still commit given that I use `Standardjs` :)

**Comment by nb** [comment]
Sure, you can, it will run `prettier` on precommit. The only problem is that if you have deep editor integration with `standard` you might see a lot of errors in the editor.

This is mostly an opportunity for me to play with `prettier` and I added a custom exception for the `peerdrop` directory in my `vim` config, which might be also worth it for you to do: https://github.com/nb/dotfiles/commit/7839ff69ef8b6a807cb746630caf9a330e3647bd The feeling of writing messy code and it being fixed by itself in few hundred milliseconds is awesome :)

**Comment by heapwolf** [comment]
I use [`Standard`](https://github.com/feross/standard) [`integrated with vim`](https://github.com/0x00A/dotfiles/blob/master/.vimrc#L220-L221), so I will see a lot of errors when I load it. Also, when I save it, Standard automatically formats it according to the Standard style.

It seems to me that Prettier and Standard have the same goals and features but with different opinions.

Since Standard seems to be winning in terms of Github Stars, and also since `Tim Berners-Lee`, who created the web, and Brenden Eich, who created javascript both endorse it, I propose that we use Standard.

**Comment by nb** [comment]
`prettier` is interesting, because it’s a pretty printer and not a fixer – it has a much stronger opinion on what the code should look like. For example, when I write super messy code:

```js
class X {f(){} g(){}
  h(){console.log('hi');} i(){} j(){}
  /* asdd */
  k(){}
}
```

prettier would give me:

```js
class X {
  f() {}
  g() {}
  h() {
    console.log('hi')
  }
  i() {}
  j() {}
  /* asdd */
  k() {}
}
```

while standard fixer:

```js
class X {
  f () {} g () {}
  h () { console.log('hi') } i () {} j () {}
  /* asdd */
  k () {}
}
```

I am not 100% sure that‘s better and that prettier won't cause long-term annoyances, that’s why I’d like to try it. But if you’re not interested in trying the same thing, feel free to close that and I will find another sandbox.

**Comment by heapwolf** [comment]
I think if i wasn't so integrated with standardjs already, i'd say yeah. Maybe move that to another sandbox and we can use Standard here almost the same why you've set it up for Prettier? (with a commit hook, etc)

**Comment by nb** [comment]
Sure :)

**Pull request closed without merging**
